### ISSUE TITLE
neden?

### ISSUE THREAD

**Issue by lostfxo** [This-null/discord-null-guard-bot#1]
command handler falan kullansan daha mantıklı olmaz mı?

**Comment by This-null** [comment]
kanka klasör klasör kim uğraşıcak git config doldur kullan neden takılıyorsun ayrı ayrı komutmu açayım

**Comment by lostfxo** [comment]
düzensiz olduğu ve okunamayacak kadar berbat gözüktüğü için olabilir mi .d

**Comment by This-null** [comment]
Yarram siktir git düzenli bul o zaman laf yapma gereksiz
